// <auto-generated />
using System;
using BlazorApp_Healthy.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp_Healthy.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp_Healthy.Shared.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TitleCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34fdf487-cde7-4605-bb2e-a92e04ca35a5"),
                            TitleCategory = "Desserts"
                        },
                        new
                        {
                            Id = new Guid("4222f1ba-4071-4fb9-a0d0-79acb5c83370"),
                            TitleCategory = "Main Courses"
                        });
                });

            modelBuilder.Entity("BlazorApp_Healthy.Shared.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bafe11ca-ff44-458f-a5b8-040c625458a6"),
                            Quantity = 1f,
                            Title = "Flour",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("11bbe7b2-4fc1-49fe-b257-970641242349"),
                            Quantity = 0.5f,
                            Title = "Sugar",
                            Unit = "kg"
                        });
                });

            modelBuilder.Entity("BlazorApp_Healthy.Shared.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IngredientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Instructons")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d9b738b-1ce6-43c6-8175-0caef2bc34f3"),
                            CategoryId = new Guid("f34b2b69-02d7-40f9-afa3-7bac7872c7af"),
                            Description = "Delicious chocolate cake recipe",
                            ImagePath = "/img/recipes/chocolate_cake.jpg",
                            IngredientId = new Guid("14bb081f-a530-41f5-a1d3-595eb458bf00"),
                            Instructons = "Mix ingredients and bake",
                            Name = "Chocolate Cake"
                        },
                        new
                        {
                            Id = new Guid("7f7cc6a4-c409-435f-be0c-e67df1a0a8b9"),
                            CategoryId = new Guid("cf3f22e0-1fb5-40de-b8b9-354d83749865"),
                            Description = "Juicy grilled chicken recipe",
                            ImagePath = "/img/recipes/grilled_chicken.jpg",
                            IngredientId = new Guid("d48d9343-7002-4ec7-a1ef-6788ef62e6a3"),
                            Instructons = "Grill the chicken with spices",
                            Name = "Grilled Chicken"
                        });
                });

            modelBuilder.Entity("BlazorApp_Healthy.Shared.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("843a2800-280b-44ef-9482-f6c476856082"),
                            FullName = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("bf44a9d5-a42c-47cd-b7ea-2069f777006d"),
                            FullName = "Jane Smith"
                        });
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.Property<Guid>("CategoriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("CategoryRecipe");
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.Property<Guid>("IngredientsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecipesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IngredientsId", "RecipesId");

                    b.HasIndex("RecipesId");

                    b.ToTable("IngredientRecipe");
                });

            modelBuilder.Entity("CategoryRecipe", b =>
                {
                    b.HasOne("BlazorApp_Healthy.Shared.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp_Healthy.Shared.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientRecipe", b =>
                {
                    b.HasOne("BlazorApp_Healthy.Shared.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp_Healthy.Shared.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
